;(a) 
(meeting ?dept (Friday . ?t)) 
;(b) 
(rule (meeting-time ?person ?day-and-time) 
      (or (meeting whole-company ?day-and-time) 
            (and (job ?p (?d . ?rest)) 
                     (meeting ?d ?day-and-time)))) 
;(c) 
(and (meeting-time (Hacker Alyssa P) (Wednesday . ?time)) 
      (meeting ?dept (Wednesday . ?time))) 